title: Yusuke Suita # your name (or website title) here
logo: "/images/6d840e3e-8cc4-40ca-b875-2d2dc3748a36.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  <br>I'm a Therapeutics Science PhD Program at Brown University. <br>
   
  <br>This website is currently under development <br>
  <a href="https://www.linkedin.com/in/yusuke-suita-841a5064/">View My LinkedIn Profile</a> 
  <a href="https://scholar.google.com/citations?hl=en&user=4DCrjY0AAAAJ">View My Google Scholar Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
